### ISSUE TITLE
high vs "low" resolusions change the look drastically

### ISSUE THREAD

**Issue by ewerybody** [ewerybody/a2#17]
This needs to be resolved somehow. When I code stuff on my laptop it may look super shitty on a HD monitor because of the windows ui scaling.
Probably ALL size setting need to be variable with a settable factor. pcheew. This is kinda hard to debug :D

**Comment by apostrophedave** [comment]
i was making a few gui related things earlier in the year (in autohotkey) and had this problem when i was switching between my laptop and desktop. the only way i found so far is to set a variable  
`Dpi := A_ScreenDpi/96`  
(if the screen setting is at 150% it will be multiplying by 1.5, if its 200% it will be multiplying by 2 etc) 
then multiply or divide any screen related values using the `Dpi` variable:  
`MouseMove, 40*Dpi, 130*Dpi` 


sometimes it needs to be divided by instead of multiply. with some, the Dpi value it isnt needed. and it doesnt seem to work at 125%... so i really dont understand whats going on, i just know it keeps things similar enough across different screen settings. 

dunno how you would go about this in python though

**Comment by ewerybody** [comment]
Hey apostrophedave! Thanks for posting!
Well, in python it depends on the package you do the UI with. So for Qt you create a QApplication which handles all windows (only 1 window in our case here. I do that in ui/a2app.py and pass the app object to the actual window in a2ui.py)
The app object has [a desktop() method](http://pyside.github.io/docs/pyside/PySide/QtGui/QApplication.html#PySide.QtGui.PySide.QtGui.QApplication.desktop). Which "Returns the desktop widget (also called the root window)" and finally this one has also functionality to handle resolutions. I do some of this now in a2clrl.adjustSizes(app) but I need much more data and maybe options to change it.

**Comment by ewerybody** [comment]
After having to do with stuff like this at work: We need a **stylesheet** to do the sizing. Probably can do it now pixel related but with a length.

**Comment by ewerybody** [comment]
http://doc.qt.io/qt-4.8/stylesheet-syntax.html

**Comment by ewerybody** [comment]
I ripped out all the hackery and tried to put it into the css. A slider is now in place to scale the ui.
TBD: save that user scale value and pre scale the ui according to the dpi from the QtApp

**Comment by ewerybody** [comment]
Finally!  9c56671 did it! Ui_scale is now persistent and the local DPI value is taken from qapp.dektop().physicalDpiX() * the saves scale value. static css is removed. Its always generated from the defaults css. Voila :]
