### ISSUE TITLE
Unexpected behaviour of hotkey's 'revert to default'

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2#191]
This is on gtranslate, but i assume it's a general thing:
![image](https://user-images.githubusercontent.com/3509308/76777985-5b78d180-67a9-11ea-8ff4-bb54024b1c59.png)
From the position of this action in the UI, i would expect this action to revert only one hotkey, not all of this module.

EXPECTED:
reverts the lower hotkey
ACTUAL:
both hotkeys are reverted.

**Comment by ewerybody** [comment]
Hello! Yeah that one was solved by having individual internal names for the different Hotlkey elements. ([See](https://github.com/ewerybody/a2.modules/commit/062304d7eb412a48caccca71fcbd06378d78e5cc))
This is still possible due to lack of checks when editing a module ☹️ super old issue #47 

fixed in next release of a2_modules!
