### ISSUE TITLE
Paste plain does not return just plain

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2#193]
It returns original instead of plain text.
When i was first trying, i got plain sometimes and original other times.
Now i get only original.

PS:
there's a checkbox ´make some awesome stuff´, seems to be leftover boilerplate code?

PPS:
@ewerybody, I commented on the closed gtranslate issue, not sure if you get notifys for closed issues...

**Comment by ewerybody** [comment]
Hey thanks for reporting!
But this is very weird. I'm unable to repro. It just works pretty reliable as expected for me. [See](https://github.com/ewerybody/a2.modules/wiki/PastePlain) 
What OS version do you have? Are you on Win 10?

on PS: regarding the `make some awesome stuff`. Pardon. Thats the default text on a Hotkey element :) [I changed it now](https://github.com/ewerybody/a2.modules/commit/a9c8b8fa252cd80ea8010e6307646c69def2cf00). 

on PPS: Yeah no worries. ;] I get notifications for everything 🌊

**Comment by ewerybody** [comment]
Hey @sirtet. I could not repro and the placeholder text has been fixed. I'm closing this for now.
cheers!

**Comment by ewerybody** [comment]
Dang I just found a way to repro this!
- In your mail web-app
- copy a **bold** formatted piece of text
- auto fire PastePlain it to an **unformatted** position
- **Voilà!** there should be at least some occurences of still bold pastes inbetween.

So at least sometimes. Kind of unreliable. Turns out there were [others experiencing this](https://autohotkey.com/board/topic/49393-clipboard-format-removal-doesnt-work/) (like 10 years ago already!) And there were attempts in working around [on reddit](https://www.reddit.com/r/AutoHotkey/comments/43jnd7/definitive_remove_formatting_from_clipboardpaste/).

One way was to blacklist via reg ex... You'd need A LOT of characters included.
Another was to white list. Which is super possible (including all weird ümläuts and stuff). But ... Do we really need this?

I just checked in an update to the script. At least in my case the occurences of still formatted pastes are much more rare!
I'll make a small release just now. So you can try out.

**Comment by ewerybody** [comment]
@sirtet: **a2.modules** has a new release!
At least the issue almost disappeared. I had a pretty solid repro on my webmail app and now I ONLY see it if I hold the PastePlain button and then the ... 20th or so paste is still bold.
