### ISSUE TITLE
Explain Project status, aim, roadmap, contribution.

### ISSUE THREAD

**Issue by sirtet** [ewerybody/a2#77]
Could you explain the project a bit more?

I am a regular ac'tivaid user, confronted with increasing problems of still using the tool (eg. screenshots on Win10 4K display) and no perspective for improvements.
So i'd like to find out if and how i could already use the project and/or how to help out.
And i guess others might be interested too?

Q1:
The project is not very visible (maybe notes/links on rumborak & tegelkamp could change that. I found the a2 project via a post in the activaid Bugtracker.). 
Are you intentionally keeping a low profile, or just not thinking about how to get more visibility / contribution?
Were there ever thoughts about getting help from c't again?

Q2:
Any infos about the timeframe to a first release, and what such a release would contain?
(Some infos for users about the latter are in plan 13.txt, some infos for coders in plan.txt)
Or a percentage done estimation?
(Some hints about this are in a2DO.txt)

Q3
The Wiki has infos about how to set up development, but not yet about how to use. Running a2_ui.exe after a2_starter.exe, i get an error about something python missing. Seems like i need some runtime thing?

**Comment by ewerybody** [comment]
Hey Sirtet! Thanks a lot for the interest!

A1:
yes. That's intended as long as it's not kind of user friendly. There is a [label](https://github.com/ewerybody/a2/issues?q=is%3Aissue+is%3Aopen+label%3Aversion1) for things I want to solve before asking for more attention. Arguable of course. Asking heise and c't is also planned.

A2:
the label thing answers a little bit about that already but with the time: It's a little like fusion energy: I'll be done in 2 weeks. Always ;] Jokes aside: I have a fulltime job which is quite demanding too! So I take as much spare time and enery as there is to do this. But I'm super excited for this to get more polish and tracktion! Some big road blocks are pretty much done #76, #57, #40, #24 will also be simpler now..
(Forget the `a2DOtxt`. I need to delete that soon. I now try to put everything into issues right away. Like it should be.) 

A3:
`a2_starter.exe` kicks off the Autohotkey runtime. Then there should be `Win+Shift+A` available to call the UI, or the `a2_ui.exe` of course.
Yes. You need [Python 3.4](https://www.python.org/downloads/release/python-343/) and PySide (in python scripts: `pip install PySide`)

That should be it.
Of course proper documentation for all this is on the list as well! Might as well be an issue.

Please excuse the current situation. It's a bit awkward. As I'm a git-n00b I checked in broken wip stuff to master instead of making a branch. So it actually worked a bit better already before I started working on #76! But I'm eager to solve this in the next days. I mean I can't use it myself right now :] that should be motivation enough.

Thanks again for your interest! I'd be super happy If you could help, coding, docing, QAing ... anything.

**Comment by sirtet** [comment]
Thanks. I will try to contact you via the chat.
Having little time too, i failed to install the python stuff, pyside does not install on python 3.5 and 3.4 is giving me headaches too, it installs, but doing pip install, i get permission errors... need to investigate later.

**Comment by ewerybody** [comment]
`pip install PySide --only-binary :all:`
was that it?
