### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by lipkau** [ewerybody/a2#97]
### Expected Behavior
When clicking on "help on a2" in the traymenu, the browser opens pointing at a specific point of README.md

### Current Behavior
When clicking on "help on a2" in the traymenu, the browser opens pointing at the root of the git repo

### Possible Solution
* adding the `<a name="desc"></a>` to README.md (removed in 3527c3f12152fe12ce3de3b697d3f7e2ed696d85)
* changing the link the menu item action points to

**Comment by ewerybody** [comment]
Oh damn.. This is a bigger issue than I though. So If your a2_settings.ahk are already written then there's gonna be a wrong link in there. I'm not writing it right now.

Basically there should only be 1 source for these links. So that should be a2_settings.ahk? Maybe we need another file where such links are in that are not crucial for a2 runtime startup.

**Comment by ewerybody** [comment]
added #98
